services:
  web:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
    restart: unless-stopped

  # Uncomment this if you want to run Redis locally
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

# Uncomment if using Redis
# volumes:
#   redis_data:
